include:
- ./func/*
kind: ArchiveUploadSpec
name: func-VaTV

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-review-fn-811161dc-19fb-4697-b6c0-32968fbb06f2
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-review-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-VaTV
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-15T20:31:07Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-review-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 3
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-review-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.user_data_review
    packageref:
      name: get-user-review-fn-811161dc-19fb-4697-b6c0-32968fbb06f2
      namespace: default
  requestsPerPod: 10000
  resources: {}
