include:
- ./func/*
kind: ArchiveUploadSpec
name: func-QaH3

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-user-review-fn-169f434e-2ce3-4408-b858-7102190e8664
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-user-review-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-QaH3
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-08T20:21:41Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-user-review-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-user-review-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.user_data_review
    packageref:
      name: get-user-review-fn-169f434e-2ce3-4408-b858-7102190e8664
      namespace: default
  requestsPerPod: 1
  resources: {}
